[project]
name = "agentchord"
version = "0.1.0"
description = "This is a multi-agent framework that effectively orchestrates agent collaborations and optimizes the settings of the agents."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.59.8",
]

[project.scripts]
agentchord = "agentchord:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
