[project]
name = "liteagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.59.8",
]

[project.scripts]
liteagent = "liteagent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
